
[workspace.dependencies]
tokio = {version = "1.48.0", features = ["full"]}
serde = { version = "1.0.228", features = ["derive"] }

[workspace]
resolver = "3"
members = ["flotilla-server","flotilla-core", "flotilla-client"]
